/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

//! Planner outputs and chunk-key template types.

use crate::core::chunk_id::ChunkId;
use crate::core::errors::SyncWriteError;

use super::requests::{CoordMap, InputArray};
use super::responses::BatchId;

/// Per-dimension index resolver strategy.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum AxisResolver {
    /// Arithmetic fast path for regular (uniformly-spaced) coordinates.
    Affine {
        /// Start value in nanoseconds.
        start_ns: i64,
        /// Step size in nanoseconds.
        step_ns: i64,
        /// Axis length.
        len: usize,
    },
    /// Hash map for irregular coordinates.
    HashMapResolver,
    /// Sorted binary search for compact immutable vectors.
    SortedBinarySearch,
}

/// Cache key for plan template lookup.
///
/// Invariant: `active_parallel_dims.len() == subset_lengths.len()`.
/// Construct via [`PlanTemplateKey::new`].
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PlanTemplateKey {
    array_id: u32,
    active_parallel_dims: Vec<String>,
    subset_lengths: Vec<usize>,
}

impl PlanTemplateKey {
    /// Create a validated key. Returns `Err` if vec lengths differ.
    pub fn new(
        array_id: u32,
        active_parallel_dims: Vec<String>,
        subset_lengths: Vec<usize>,
    ) -> Result<Self, SyncWriteError> {
        if active_parallel_dims.len() != subset_lengths.len() {
            return Err(SyncWriteError::Validation {
                message: format!(
                    "active_parallel_dims length {} != subset_lengths length {}",
                    active_parallel_dims.len(),
                    subset_lengths.len()
                ),
            });
        }
        Ok(Self {
            array_id,
            active_parallel_dims,
            subset_lengths,
        })
    }

    /// Array namespace identifier.
    #[must_use]
    pub fn array_id(&self) -> u32 {
        self.array_id
    }

    /// Active parallel dimension names (sorted).
    #[must_use]
    pub fn active_parallel_dims(&self) -> &[String] {
        &self.active_parallel_dims
    }

    /// Subset lengths along each parallel dimension.
    #[must_use]
    pub fn subset_lengths(&self) -> &[usize] {
        &self.subset_lengths
    }
}

/// Cached plan template for repeated write patterns.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub struct PlanTemplate {
    /// Dimension ordering for mixed-radix enumeration.
    pub dim_order: Vec<String>,
    /// Mixed-radix strides per dimension.
    pub radix_strides: Vec<u64>,
    /// Total number of tasks generated by this template.
    pub task_count: usize,
}

/// Resolved tuple chunk key computed at write time.
///
/// Represents the per-dimension chunk indices (e.g., `[0, 4, 0, 0]`)
/// that become the on-disk Zarr chunk path (e.g., `"0.4.0.0"` for v2 dot separator).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TupleChunkKey {
    /// Per-dimension chunk indices in canonical `dim_order`.
    indices: Vec<usize>,
}

impl TupleChunkKey {
    /// Create a new tuple chunk key from dimension indices.
    #[must_use]
    pub fn new(indices: Vec<usize>) -> Self {
        Self { indices }
    }

    /// Per-dimension chunk indices.
    #[must_use]
    pub fn indices(&self) -> &[usize] {
        &self.indices
    }

    /// Render as separator-joined string (e.g., `"0.4.0.0"` for `'.'`).
    #[must_use]
    pub fn render(&self, separator: char) -> String {
        self.indices
            .iter()
            .map(usize::to_string)
            .collect::<Vec<_>>()
            .join(&separator.to_string())
    }

    /// Compute the C-order linear index: `sum(indices[i] * divisors[i])`.
    pub fn linear_index(&self, divisors: &[u64]) -> Result<u64, SyncWriteError> {
        if self.indices.len() != divisors.len() {
            return Err(SyncWriteError::Validation {
                message: format!(
                    "tuple key length {} != divisors length {}",
                    self.indices.len(),
                    divisors.len()
                ),
            });
        }
        let mut linear = 0_u64;
        for (idx, div) in self.indices.iter().zip(divisors) {
            let idx_u64 = u64::try_from(*idx).map_err(|_| SyncWriteError::ChunkIdOverflow)?;
            linear = linear
                .checked_add(
                    idx_u64
                        .checked_mul(*div)
                        .ok_or(SyncWriteError::ChunkIdOverflow)?,
                )
                .ok_or(SyncWriteError::ChunkIdOverflow)?;
        }
        Ok(linear)
    }
}

/// Pre-computed per-array template for O(num_parallel_dims) chunk key resolution.
/// Built once at `add_array()` from registered coordinates; immutable after creation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ChunkKeyTemplate {
    /// Canonical dimension order (parallel dims first in canonical order,
    /// then non-parallel dims alphabetically).
    dim_order: Vec<String>,
    /// Chunk counts per dimension.
    /// Parallel dims: length of registered coordinate axis.
    /// Non-parallel dims: always 1 (single chunk spanning full axis).
    axis_lengths: Vec<usize>,
    /// Pre-computed C-order divisors for linear ↔ tuple conversion.
    /// `divisors[i] = product(axis_lengths[i+1..])`.
    divisors: Vec<u64>,
    /// Indices of parallel dimensions within `dim_order`.
    parallel_dim_positions: Vec<usize>,
    /// Fixed tuple indices for non-parallel dimensions: `(position_in_dim_order, index)`.
    /// Index is always 0 for single-chunk non-parallel axes.
    fixed_nonparallel_indices: Vec<(usize, usize)>,
}

impl ChunkKeyTemplate {
    #[cfg(test)]
    pub(crate) fn from_parts_for_test(
        dim_order: Vec<String>,
        axis_lengths: Vec<usize>,
        divisors: Vec<u64>,
        parallel_dim_positions: Vec<usize>,
        fixed_nonparallel_indices: Vec<(usize, usize)>,
    ) -> Self {
        Self {
            dim_order,
            axis_lengths,
            divisors,
            parallel_dim_positions,
            fixed_nonparallel_indices,
        }
    }

    /// Build from registered coordinates and canonicalized parallel dims.
    /// Returns `Err` if coords are empty or axis lengths overflow.
    pub fn build(
        registered_coords: &CoordMap,
        active_parallel_dims: &[String],
    ) -> Result<Self, SyncWriteError> {
        // Build dim_order: parallel dims first, then non-parallel alphabetically.
        let mut dim_order = Vec::with_capacity(registered_coords.len());
        for dim in active_parallel_dims {
            dim_order.push(dim.clone());
        }
        // Non-parallel dims: all registered keys not in active_parallel_dims, sorted.
        let mut nonparallel: Vec<String> = registered_coords
            .keys()
            .filter(|k| !active_parallel_dims.contains(k))
            .cloned()
            .collect();
        nonparallel.sort();
        dim_order.extend(nonparallel);

        // Build axis_lengths and track positions.
        let mut axis_lengths = Vec::with_capacity(dim_order.len());
        let mut parallel_dim_positions = Vec::with_capacity(active_parallel_dims.len());
        let mut fixed_nonparallel_indices = Vec::new();

        for (pos, dim) in dim_order.iter().enumerate() {
            let is_parallel = active_parallel_dims.contains(dim);
            let coord_values =
                registered_coords
                    .get(dim.as_str())
                    .ok_or_else(|| SyncWriteError::Validation {
                        message: format!("dimension '{dim}' not found in registered coords"),
                    })?;
            if is_parallel {
                parallel_dim_positions.push(pos);
                axis_lengths.push(coord_values.len());
            } else {
                // Non-parallel dims are always a single chunk.
                axis_lengths.push(1);
                fixed_nonparallel_indices.push((pos, 0));
            }
        }

        // Compute C-order divisors: divisors[i] = product(axis_lengths[i+1..]).
        let ndim = axis_lengths.len();
        let mut divisors = vec![1_u64; ndim];
        if ndim > 1 {
            for i in (0..ndim - 1).rev() {
                let next_len = u64::try_from(axis_lengths[i + 1])
                    .map_err(|_| SyncWriteError::ChunkIdOverflow)?;
                divisors[i] = divisors[i + 1]
                    .checked_mul(next_len)
                    .ok_or(SyncWriteError::ChunkIdOverflow)?;
            }
        }

        Ok(Self {
            dim_order,
            axis_lengths,
            divisors,
            parallel_dim_positions,
            fixed_nonparallel_indices,
        })
    }

    /// Resolve a tuple chunk key from parallel dimension axis indices.
    ///
    /// `parallel_axis_indices` must have the same length as `parallel_dim_positions`
    /// and contain the resolved axis index for each parallel dimension (in the same order).
    ///
    /// Non-parallel dimension indices are filled from `fixed_nonparallel_indices`.
    pub fn resolve_tuple_key(
        &self,
        parallel_axis_indices: &[usize],
    ) -> Result<TupleChunkKey, SyncWriteError> {
        if parallel_axis_indices.len() != self.parallel_dim_positions.len() {
            return Err(SyncWriteError::Validation {
                message: format!(
                    "parallel_axis_indices length {} != parallel_dim_positions length {}",
                    parallel_axis_indices.len(),
                    self.parallel_dim_positions.len()
                ),
            });
        }
        let mut indices = vec![0_usize; self.dim_order.len()];

        // Fill parallel positions.
        for (i, &pos) in self.parallel_dim_positions.iter().enumerate() {
            indices[pos] = parallel_axis_indices[i];
        }

        // Fill non-parallel positions (always 0).
        for &(pos, fixed_idx) in &self.fixed_nonparallel_indices {
            indices[pos] = fixed_idx;
        }

        Ok(TupleChunkKey::new(indices))
    }

    /// Compute the C-order linear index for a given tuple key.
    pub fn linear_from_tuple(&self, tuple: &TupleChunkKey) -> Result<u64, SyncWriteError> {
        tuple.linear_index(&self.divisors)
    }

    /// Unravel a linear index back to a tuple key using this template's axis lengths.
    pub fn tuple_from_linear(&self, linear: u64) -> Result<TupleChunkKey, SyncWriteError> {
        let ndim = self.axis_lengths.len();
        let mut indices = vec![0_usize; ndim];
        let mut remaining = linear;

        for (slot, div) in indices.iter_mut().zip(&self.divisors) {
            if *div == 0 {
                return Err(SyncWriteError::Validation {
                    message: "divisor is zero during unravel".to_string(),
                });
            }
            let idx = remaining / div;
            remaining %= div;
            *slot = usize::try_from(idx).map_err(|_| SyncWriteError::ChunkIdOverflow)?;
        }

        if remaining != 0 {
            return Err(SyncWriteError::Validation {
                message: format!(
                    "linear index {linear} exceeds chunk grid (remainder {remaining})"
                ),
            });
        }

        Ok(TupleChunkKey::new(indices))
    }

    /// Canonical dimension order.
    #[must_use]
    pub fn dim_order(&self) -> &[String] {
        &self.dim_order
    }

    /// Chunk counts per dimension.
    #[must_use]
    pub fn axis_lengths(&self) -> &[usize] {
        &self.axis_lengths
    }

    /// C-order divisors.
    #[must_use]
    pub fn divisors(&self) -> &[u64] {
        &self.divisors
    }

    /// Indices of parallel dimensions within `dim_order`.
    #[must_use]
    pub fn parallel_dim_positions(&self) -> &[usize] {
        &self.parallel_dim_positions
    }

    /// Fixed non-parallel dimension indices.
    #[must_use]
    pub fn fixed_nonparallel_indices(&self) -> &[(usize, usize)] {
        &self.fixed_nonparallel_indices
    }
}

/// A single chunk write task dispatched to the worker pool.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub struct ChunkTask {
    /// Write batch this task belongs to.
    pub batch_id: BatchId,
    /// Target array name.
    pub array_name: String,
    /// Target chunk identity.
    pub chunk_id: ChunkId,
    /// Resolved tuple chunk key (e.g., `[0, 4, 0, 0]`).
    pub tuple_key: TupleChunkKey,
    /// Required buffer bytes for this task.
    pub required_bytes: usize,
    /// Input array data to copy.
    pub input: InputArray,
}

/// Planned write batch produced by the chunk planner.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub struct PlannedWriteBatch {
    /// Unique batch identifier.
    pub batch_id: BatchId,
    /// All chunk IDs in this batch (for atomic reservation).
    pub chunk_ids: Vec<ChunkId>,
    /// Individual chunk tasks to dispatch.
    pub tasks: Vec<ChunkTask>,
}

/// Rendered chunk path specification.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub struct ChunkPathSpec {
    /// Relative path from dataset root to the chunk file.
    pub relative_path: String,
}

/// Rendered metadata path specification.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub struct MetadataPathSpec {
    /// Metadata file paths for the root group node.
    pub root_paths: Vec<String>,
    /// Metadata file paths for each array node.
    pub per_array_paths: Vec<String>,
}
