name: Docker Base Image

on:
  push:
    branches: [main]
    paths:
      - Dockerfile.Earth2Studio.runtime-base
  pull_request:
    branches: [main]
    paths:
      - Dockerfile.Earth2Studio.runtime-base
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUNTIME_BASE_TAG: pytorch-26.01-py3-th0.8.1
  PYTORCH_BASE_IMAGE: nvcr.io/nvidia/pytorch:26.01-py3

jobs:
  build-base:
    name: Build & Push Runtime Base
    runs-on: linux-amd64-cpu16
    steps:
      - uses: actions/checkout@v4

      - name: Log in to NGC registry
        run: echo "${{ secrets.NGC_REGISTRY_PASSWORD }}" | docker login ${{ vars.NGC_REGISTRY }} -u '$oauthtoken' --password-stdin

      - name: Build runtime base image
        run: |
          docker build \
            -f Dockerfile.Earth2Studio.runtime-base \
            --build-arg PYTORCH_BASE_IMAGE=${{ env.PYTORCH_BASE_IMAGE }} \
            -t ${{ vars.NGC_REGISTRY }}/${{ secrets.NGC_ORG }}/${{ secrets.NGC_RUNTIME_BASE_IMAGE }}:${{ env.RUNTIME_BASE_TAG }} \
            .

      - name: Push runtime base image
        if: github.event_name != 'pull_request'
        run: docker push ${{ vars.NGC_REGISTRY }}/${{ secrets.NGC_ORG }}/${{ secrets.NGC_RUNTIME_BASE_IMAGE }}:${{ env.RUNTIME_BASE_TAG }}
